import { dark, dark_primary, primary } from "@/constants/Colors";
import { useDefault } from "@/hooks/useDefault";
import { height } from "@/utils/dimensions";
import React, { type Dispatch, type FC, type SetStateAction, useCallback } from "react";
import {
	Linking,
	Modal,
	SafeAreaView,
	ScrollView,
	StyleSheet,
	Text,
	TouchableOpacity,
	View,
} from "react-native";

interface TermsAndConditionsProps {
	showModal: boolean;
	setShowModal: Dispatch<SetStateAction<boolean>>;
}

export const TermsAndConditions: FC<TermsAndConditionsProps> = ({ showModal, setShowModal }) => {
	const { language } = useDefault();

	const handleClose = useCallback(() => {
		setShowModal(false);
	}, [setShowModal]);

	// Handle back button press via Modal's onRequestClose prop

	return (
		<Modal
			visible={showModal}
			transparent={true}
			animationType="fade"
			onRequestClose={handleClose}>
			<View style={styles.backdrop}>
				{language === "english" && (
					<SafeAreaView style={styles.container}>
						<View style={styles.modalContent}>
							{/* Header */}
							<View style={styles.header}>
								<Text style={styles.title}>Terms and Conditions</Text>
							</View>

							{/* Scrollable Content */}
							<ScrollView
								style={styles.scrollContainer}
								showsVerticalScrollIndicator={true}>
								<View style={styles.content}>
									<Text style={styles.mainTitle}>
										TERMS AND CONDITIONS FOR LOAN SERVICES
									</Text>

									<Text style={styles.paragraph}>
										The Website is owned and operated by MoneyTime Technology
										Solutions Pvt. Ltd. (&quot;MTTS&quot;), a Loan Service
										Provider (&quot;LSP&quot;) registered under the Companies
										Act, 2013, CIN No U62099MH2025PTC447819. MTTS acts solely as
										a Loan Service Provider and is not involved in sanctioning,
										underwriting, or pricing of loans. These functions are
										solely undertaken by our partnered Regulated Entities
										(&quot;RE&quot;).
									</Text>

									<Text style={styles.paragraph}>
										This document / terms of use (&quot;Terms&quot;) sets forth
										the general terms and conditions that apply to the access
										and use of website at <Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("https://www.rapidmoney.in")}>https://www.rapidmoney.in</Text>{" "}
										(&quot;Website&quot;) and its mobile application
										&apos;RapidMoney.&apos; (&quot;App&quot;) powered by
										MoneyTime Technology Solutions Pvt. Ltd. (herewith referred
										as MTTS). The Terms constitute a legally binding agreement
										between users accessing the App / Website (&quot;you&quot; /
										&quot;your&quot; / &quot;user&quot;) and Company regarding
										your use of the App, Website and other associated services.
									</Text>

									<Text style={styles.paragraph}>
										This Agreement is an electronic record in terms of
										Information Technology Act, 2000 and generated by a computer
										system and does not require any physical or digital
										signatures; and any amendments made thereunder, that
										provides for the due diligence to be exercised for the
										access or usage of App and Website. Further, please be
										advised that these Terms of Use are made available to the
										User pursuant to and in accordance with the provisions of
										Rule 3 (1) of the Information Technology (Intermediaries
										Guidelines) Rules, 2011 that require publishing the rules,
										regulations, privacy policy and terms of use for access or
										usage of the Website.
									</Text>

									<Text style={styles.paragraph}>
										The Company reserves the right, at its discretion, to
										change, modify, add, or remove portions of (i) these Terms
										at any time by posting the amended Terms; and (ii) contents
										on App / Website. If any of these conditions shall be deemed
										invalid, void, or for any reason unenforceable, that
										condition shall be deemed severable and will not affect the
										validity and enforceability of any remaining conditions.
										Please check these Terms periodically for changes. Your
										continued use of the App and Website after the posting of
										changes constitutes your binding acceptance of such changes.
										In addition, when using any particular services, you may be
										subject to any posted guidelines or rules applicable to such
										services. All such guidelines or rules are hereby
										incorporated by reference into the Terms. If you do not
										agree with the Terms, please do not use this Website, App or
										Services.
									</Text>

									<Text style={styles.paragraph}>
										By utilizing the services provided by MoneyTime Technology
										Solutions Pvt. Ltd., you hereby consent to the collection,
										use, and disclosure of your personal and financial
										information to our affiliates and partners, for the purpose
										of offering additional financial products and services
										including providing a loan.
									</Text>

									<Text style={styles.paragraph}>
										MoneyTime Technology Solutions Pvt. Ltd. is committed to
										safeguarding your privacy and will process your data in
										strict accordance with our Privacy Policy. By continuing to
										use the application, you acknowledge and expressly agree to
										the use of your data for cross-selling and other related
										purposes as outlined in these terms.
									</Text>

									<Text style={styles.paragraph}>
										PLEASE READ THESE TERMS OF USE. BY ACCESSING OR BY CLICKING
										ON &apos;SUBMIT&apos; / &apos;I AGREE&apos; OR ANY SIMILAR
										TAB ON THE APP / WEBSITE, YOU AGREE TO THESE TERMS CONTAINED
										HEREIN CONSTITUTES WHICH FORMS THE AGREEMENT BETWEEN YOU AND
										THE COMPANY FOR THE SERVICES AS DEFINED HEREUNDER.
									</Text>

									<Text style={styles.paragraph}>
										The company will retain and use your information as
										necessary to comply with our legal obligations, resolve
										disputes and enforce our agreements entered into for
										providing Services and ancillary services.
									</Text>

									<Text style={styles.sectionTitle}>1. Customer Eligibility</Text>

									<Text style={styles.numberedItem}>
										1.1 Use of the application/website is available only to such
										persons who can legally contract under Indian Contract Act,
										1872. Persons who are &quot;incompetent to contract&quot;
										within the meaning of the Indian Contract Act, 1872
										including minors, un-discharged insolvent etc. shall not be
										eligible to use the application/website. If the person
										accessing the application/website is a minor. i.e., under
										the age of 18 (eighteen) years, such person shall not
										register as a Participant(s) of the application/website and
										shall not transact on or use the application/website.
									</Text>

									<Text style={styles.numberedItem}>
										1.2 The application/website reserves the right to terminate
										any membership and/or refuse to provide access to the
										application/website if it is brought to the notice or if it
										is discovered that the individual accessing/using the
										application/website is under the age of 18 (eighteen) years.
									</Text>

									<Text style={styles.numberedItem}>
										1.3 By accepting the Terms of Use (<Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("https://www.rapidmoney.in")}>https://www.rapidmoney.in</Text>), the
										Participant(s) irrevocably declares and undertakes that: (i)
										he/she is above 18 (eighteen) years of age; (ii) he/she/ it
										has the authority to enter into this Agreement; (ii) this
										Agreement is binding and enforceable against the
										Participant(s); (iii) execution of this Agreement by the
										Participant(s) does not conflict with any of the
										Participant(s)&apos;s obligation under any Applicable Laws,
										contract or otherwise; and (iii) the Participant(s) has
										read, understood and agreed to abide by the Privacy Policy,
										which is available{" "}
  <Text
    style={{ color: dark_primary, textDecorationLine: "underline" }}
    onPress={() =>
      Linking.openURL("https://www.rapidmoney.in/privacy-policy/")
    }
  >
    here
  </Text>
  {" "}and incorporated by reference (the &quot;Privacy Policy&quot;) in
  the website.
</Text>

									<Text style={styles.numberedItem}>
										1.4 The Participant(s) must have a rupee denominated
										savings/current account with a bank in India.
									</Text>

									<Text style={styles.numberedItem}>
										1.5 Participant(s) must have PAN (Permanent Account Number),
										allotted by Income Tax Department of India and/or Aadhar or
										any other valid documents(OVD) as per RBI&apos;s KYC
										Guidelines
									</Text>

									<Text style={styles.numberedItem}>
										1.6 By accepting the Terms of Use, Participants acknowledge
										that they have also read and understood the risks involved
										in borrowing through the application/website.
									</Text>

									<Text style={styles.numberedItem}>
										1.7 To be eligible as a Borrower, Participant(s) must
										qualify the below criteria along with criteria mentioned
										below:
									</Text>

									<Text style={styles.numberedItem}>
										1.8 The Participant(s): (a) must be based in India; (b)
										should not be unemployed/out of business at any point of
										time during the last 6 (six) months; (c) should not have any
										kind of civil or criminal litigation instituted against
										him/her.
									</Text>

									<Text style={styles.sectionTitle}>
										2. Sign up and Registration
									</Text>

									<Text style={styles.numberedItem}>
										2.1 As indicated, any person may access the
										application/Website either by registering or using the
										application/Website as a guest. However, a guest user may
										not have access to all sections of the Website which shall
										be reserved only for the purpose of registered Users, and
										which may change from time to time at the sole discretion of
										the application/Website.
									</Text>

									<Text style={styles.numberedItem}>
										2.2 All eligible users who wish/have to register themselves
										with the application/Website shall be required to create an
										account by filling in the details prescribed in the
										application.
									</Text>

									<Text style={styles.numberedItem}>
										2.3 By applying for registration, the User agrees and
										authorizes MoneyTime Technology Solutions Pvt. Ltd./ Lending
										partners of MoneyTime Technology Solutions Pvt. Ltd. to
										carry out such checks and verification. As part of the
										registration process:
									</Text>

									<Text style={styles.subNumberedItem}>
										2.3.1 Identity, KYC, fraud checks in the application will be
										redirected and decision will be taken by partnered Regulated
										Entities;
									</Text>

									<Text style={styles.subNumberedItem}>
										2.3.2 obtain a credit report for Users from the Credit
										Information Bureau
									</Text>

									<Text style={styles.numberedItem}>
										2.4 If any User provides any information that is untrue,
										false, not updated, and incomplete or the
										application/Website has reasonable grounds to believe that
										such information is untrue, false, not updated, incomplete,
										the Company shall have the right to suspend or terminate the
										relevant User account and refuse any and all current or
										future use of the application/Website (or any portion
										thereof).
									</Text>

									<Text style={styles.numberedItem}>
										2.5 Users of the application/Website may be required to
										provide certain personal information and expressly permit
										the application/Website for accessing and/or collecting and
										retaining such personal information of the Users. Such
										provision and/or collection, storage, retention, use and
										disclosure of the personal information of the Users shall be
										subject to the application/Website&apos;s privacy policy
										available (<Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("https://www.rapidmoney.in/privacy-policy/")}>https://www.rapidmoney.in/privacy-policy/</Text>)
									</Text>

									<Text style={styles.numberedItem}>
										2.6 Non-Lending/Non-Regulated Services:{"\n"}MoneyTime
										Technology Solutions Pvt. Ltd. may provide non-lending or
										non-regulated products directly through the Platform. Please
										note that accessing these Services does not guarantee Credit
										Facility approval by the Lending Partners. Additionally,
										once a non-regulated Service (i.e. a Service not being a
										Lending Service) is accessed in accordance with this clause,
										no requests for refunds or cancellations for the purchase of
										Services will be entertained.
									</Text>

									<Text style={styles.sectionTitle}>3. Use of Website</Text>

									<Text style={styles.numberedItem}>
										3.1 To borrow through the App/Website You must log on to{" "}
										<Text
											style={[styles.numberedItem, { color: dark_primary, textDecorationLine: "underline" }]}
											onPress={() => Linking.openURL("https://web.rapidmoney.in/borrower/login")}>
											https://web.rapidmoney.in/borrower/login
										</Text>
										.
									</Text>

									<Text style={styles.numberedItem}>
										3.2 All registered Users of the App/Website shall be solely
										responsible for activities relating to the account and the
										App/Website or the entity operating the same shall not in
										any manner be held responsible and/or liable for any illegal
										acts including but not limited to misuse, unauthorized
										access, hacking of the App/Website or refusal to access the
										App/Website due to such reason.
									</Text>

									<Text style={styles.numberedItem}>
										3.3 All App/Website borrowers (Loan Sanctioned borrowers)
										hereby confirm and acknowledge that they have been provided
										with a copy of the Key Fact Statement and Loan Agreement to
										be entered between the Borrower and the Lender/s partnered
										with the Regulated Entities. All Users further confirm that
										have read and understood all the terms and conditions and
										upon execution do hereby covenant and undertake to
										unconditionally abide by the same, without raising any
										defense of whatsoever nature in respect thereof.
									</Text>

									<Text style={styles.numberedItem}>
										3.4 If any User learns or is made or becomes aware of any
										instance of hacking or misuse of its Account, it shall
										without delay notify the App/Website of the same.
									</Text>

									<Text style={styles.numberedItem}>
										3.5 We can refuse to act on any instruction received from
										User that we believe: (a) was unclear; (b) was not given by
										the user; (c) might cause us to breach a legal or other
										duty; or (d) suggests that the App/Website is being used for
										an illegal purpose.
									</Text>

									<Text style={styles.numberedItem}>
										3.6 The App/Website disclaims, and the User waives off, any
										and all claims/liabilities arising out of any unlawful usage
										of the App/Website, the personal information of the User,
										inaccessibility of the App/Website for any reason
										whatsoever, which are caused owing to causes beyond the
										control of the App/Website . While the App/Website employs
										best efforts to ensure the aforesaid, it cannot guarantee
										the same. No User shall trade or sell such User accounts in
										any manner whatsoever.
									</Text>

									<Text style={styles.numberedItem}>
										3.7 Notwithstanding anything contained herein, the
										App/Website may be inaccessible for such purposes as it may,
										at its sole discretion deem necessary, including but not
										limited to regular maintenance. The App/Website may intimate
										the Users from time to time regarding such inaccessibility.
										However, under no circumstances will the App/Website be held
										liable for any losses or claims arising out of such
										inaccessibility to the Users, and the User expressly waives
										off any and all claims/liabilities arising to this end.
									</Text>

									<Text style={styles.numberedItem}>
										3.8 The App/Website grants every User a limited,
										non-exclusive and revocable license to access the
										App/Website and only to the extent such use does not violate
										these Terms of Use including, without limitation, the
										prohibitions listed in clause 6.1 of the Terms of Use.
									</Text>

									<Text style={styles.numberedItem}>
										3.9 The User shall solely be responsible for obtaining
										access to the App/Website, and that access may involve
										third-party fees (such as internet service provider fees or
										airtime charges). In addition, the User must provide and
										shall be responsible for all equipment necessary to access
										the App/Website. The User may not bypass any measures that
										have been implemented to prevent or restrict access to this
										App/Website.
									</Text>

									<Text style={styles.numberedItem}>
										3.10 Any unauthorized use and/or access of/to the
										App/Website by a User (including any access through the
										registered account of that User or any device that the User
										may use to access the App/Website) shall terminate the
										permission or license granted to the User by the
										App/Website.
									</Text>

									<Text style={styles.numberedItem}>
										3.11 Under no circumstance shall any User save copies,
										download, and print or otherwise store any content of the
										App/Website for any commercial purposes. Accessing,
										downloading, storing, or otherwise using the content of the
										App/Website for any commercial purpose will constitute a
										material breach of these terms & conditions.
									</Text>

									<Text style={styles.numberedItem}>
										3.12 The App/Website strictly prohibits any use of the
										content available through the App/Website, including but not
										limited to: (i) any downloading, copying or other use of the
										content or the App/Website for purposes competitive to the
										App/Website or for the benefit of any third party; (ii) any
										caching, unauthorized linking to the App/Website or the
										framing of any content available on the App/Website; (iii)
										any modification, distribution, transmission, performance,
										broadcast, publication, uploading, licensing, reverse
										engineering, transfer or sale of, or the creation of
										derivative works from, any content, products or Services
										obtained from the App/Website that the User does not have a
										right to make available (such as the intellectual property
										of another party); (iv) any uploading, posting or
										transmitting of any material that contains software viruses
										or any other computer code, files or programs designed to
										interrupt, destroy or limit the functionality of any
										computer; (v) using any hardware or software intended to
										surreptitiously intercept or otherwise obtain any
										information (such as system data or personal information)
										from the App/Website (including, but not limited to the use
										of any &quot;scraping&quot; or other data mining techniques,
										robots or similar data gathering and extraction tools); or
										(vi) any action that imposes or may impose (in the
										Website&apos;s sole discretion) an unreasonable or
										disproportionately large load on the Website&apos;s
										infrastructure, or damage or interfere with the proper
										working of the Website&apos;s infrastructure.
									</Text>

									<Text style={styles.numberedItem}>
										3.13 The App/Website reserves the right to refuse or cancel
										any registration of its Users, remove any person from the
										App/Website and prohibit any person from using the
										App/Website for any reason whatsoever, and to limit or
										terminate such access to or use of the App/Website at any
										time without notice.
									</Text>

									<Text style={styles.sectionTitle}>
										4. Terms and Conditions for Borrowings
									</Text>

									<Text style={styles.numberedItem}>
										4.1 You can borrow from the App/Website by posting a loan
										request through the App/Website and completing the
										application process.
									</Text>

									<Text style={styles.numberedItem}>
										4.2 During the application process, you must also enter the
										details of your bank account for the purposes of repayments
										due to the lender.
									</Text>

									<Text style={styles.numberedItem}>
										4.3 By posting Loan Request, you agree:
									</Text>

									<Text style={styles.listItem}>
										a) to provide us with certain additional Information
										which we will ask you for, and that if we discover that this
										additional information and/or the information you gave us
										during the application process was inaccurate or deficient
										in any respect, then the Loan Request will be void and we
										have the right to take appropriate actions against the
										Users.
									</Text>
									<Text style={styles.listItem}>
										b) to authorize us to check your credit bureau report
										from any of the Credit Information Bureau in India, which
										are required by us to assess the credibility of the
										repayments.
									</Text>

									<Text style={styles.numberedItem}>
										4.4 Formation of Key Fact Statement and Loan Agreements
									</Text>

									<Text style={styles.listItem}>
										a) The Borrower agrees to accept each of the loan offers
										that meets the borrowing criteria.
									</Text>
									<Text style={styles.listItem}>
										b) The Borrower agrees to sign and execute the Key Fact
										Statement and Loan Agreements electronically. In case of
										multiple loan agreements, the App/Website will provide you
										with a summary of loan availed.
									</Text>

									<Text style={styles.numberedItem}>
										4.5 Disbursement of Loan proceeds upon execution of all the
										required documents and fulfillment of all conditions for
										disbursements, to the sole satisfaction of the partnered
										Regulated Entity, the borrowed amount will be credited to
										the account of the Borrower by the partnered Regulated
										Entity, subject to its credit evaluation and discretion.
										They follow a rounding down approach during loan
										disbursement to the borrower for simplicity purposes. For
										eg, if the disbursement amount after deduction of all
										charges and fees amounts to Rs. 9411.18, the disbursement
										amount will be Rs. 9,411 and Rs. 0.18 will be transferred to
										the lending partner as the adjustment amount.
									</Text>

									<Text style={styles.numberedItem}>
										4.6 Charges and Fees: Charges will follow the terms outlined
										in the loan agreements between borrowers and lenders, and
										the charges will be passed on to the lending partners.
									</Text>

									<Text style={styles.listItem}>
										For Personal Loan (MoneyTime Technology Solutions Pvt.
										Ltd.): (i) processing fee: upto 15% at the time of
										disbursement.
									</Text>
									<Text style={styles.listItem}>
										Any other charges including delay charges shall be as per
										the terms of loan agreements entered into by the borrowers,
										the lenders partnered with Regulated Entity.
									</Text>
									<Text style={styles.listItem}>
										Litigation costs and expenses, including legal fees and
										expenses, to cover litigation recover outstanding arrears,
										in which case the Borrower will be advised of such costs and
										expenses if such action proves necessary.
									</Text>
									<Text style={styles.listItem}>
										Late Payment Fee: If a Borrower has delayed a repayment,
										Partnered Regulated Entity reserves the right to charge you
										an administration fee for the work it does in attempting to
										collect your Repayments (&quot;Late Payment Fee&quot;).
									</Text>

									<Text style={styles.sectionTitle}>
										5. Refund and Cancellation policy:
									</Text>

									<Text style={styles.listItem}>
										a) The borrowers can raise a refund request in case there
										is a double deduction of EMI for a due date. This normally
										happens when the payment is received by the lending partners
										via auto-debit mode and the borrower makes payment on their
										own. The request can be raised by writing to customer
										support at <Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("mailto:support@rapidmoney.in")}>support@rapidmoney.in</Text> on such debits from the
										account. If a refund is eligible, it shall be processed by
										the lending partner within 2 (two) days of resolution.
									</Text>
									<Text style={styles.listItem}>
										b) In case of a payment failure, (where payment is not
										received by the lending partner), but the amount is deducted
										from the customer&apos;s bank account, it will be
										automatically refunded by the payment gateway as per their
										policy. The customer can reach out to the payment
										gateway&apos;s customer support team for a speedy resolution
										in this case.
									</Text>
									<Text style={styles.sectionTitle}>6. Loan Administration</Text>

									<Text style={styles.numberedItem}>
										6.1 EMI: EMIs will start as per the date of disbursement of
										the loan.
									</Text>

									<Text style={styles.numberedItem}>
										6.2 Prepayment Terms : A borrower wishing to prepay or
										foreclose their loan may do so by settling the foreclosure
										charges as specified in the agreement between the lender and
										the borrower and any other charges and dues, will apply.
									</Text>

									<Text style={styles.numberedItem}>6.3 Missed Repayments</Text>

									<Text style={styles.paragraph}>
										In case a Borrower misses a repayment or anticipates that
										for any reason whatsoever the Borrower will not be able to
										repay as per the repayment schedule under the Loan
										Agreement, then the Borrower should promptly contact the
										Company by sending an email to <Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("mailto:support@rapidmoney.in")}>support@rapidmoney.in</Text> Upon
										receipt, of the e-mail, our partnered regulated entities
										along with its Lending Service Provider; MoneyTime
										Technology Solutions Pvt. Ltd., shall undertake the
										following actions:
									</Text>

									<Text style={styles.listItem}>
										a) explain the delay charges and options available with
										you
									</Text>
									<Text style={styles.listItem}>
										b) inform the relevant lending partner regarding the same
									</Text>
									<Text style={styles.listItem}>
										c) inform if your account is being passed on to the
										internal recovery team for further legal recovery as your
										loan has been classified under Default category.
									</Text>
									<Text style={styles.listItem}>
										d) Inform the Credit Information Bureau about the
										Borrower&apos;s default in repayment. As a word of caution,
										we would like to inform you that this reporting may have
										serious consequences on your ability to avail any credit in
										the future.
									</Text>

									<Text style={styles.numberedItem}>6.4 Default Category</Text>

									<Text style={styles.paragraph}>
										A Borrower shall be considered under &quot;default&quot;
										category, if either of the below event has occurred:
									</Text>

									<Text style={styles.listItem}>
										a) if he fails to pay the EMI for three consecutive
										months;
									</Text>
									<Text style={styles.listItem}>
										b) we receive confirmation that the Borrower has died;
									</Text>
									<Text style={styles.listItem}>
										c) the Borrower has entered into a terminal arrangement
										affecting the Borrower&apos;s Loan Agreements
									</Text>
									<Text style={styles.listItem}>
										d) Other specific situations, which may arise at any
										point in time, the partnered Regulated Entity will have the
										right to classify the loan as default, with support from
										MTTS in its capacity as a Loan Service Provider and mutually
										agreed in the agreement.
									</Text>
									<Text style={styles.sectionTitle}>7. Closing Your Account</Text>

									<Text style={styles.numberedItem}>
										7.1 Once your Loan is repaid, you may terminate your
										registration by sending us an email to <Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("mailto:support@rapidmoney.in")}>support@rapidmoney.in</Text>{" "}
										and you will no longer be able to access the App/Website.
										However, the lending partner and the company will continue
										to maintain records to the extent that we are required by
										law and internal policies and agreements partnered with
										Regulated Entities.
									</Text>

									<Text style={styles.numberedItem}>
										7.2 We may terminate the registration of the User if the
										User has provided false information, has breached the Terms
										of Use, has died, become bankrupt, failed to pay the loan,
										or it is categorized in Default category on the App/Website
										or the partnered Regulated Entity has classified the user
										under default category, make a voluntary arrangement with
										anyone the User owes money, or the User establishes contact
										with anyone who owes money to the User without knowledge of
										the App/Website.
									</Text>

									<Text style={styles.numberedItem}>
										7.3 We may either terminate or suspend your registration
										immediately and without notice if we are aware or reasonably
										suspect that you are engaged in, or may be the victim of,
										any fraudulent activity or we find that you are spoiling the
										reputation of the app/website or we find any activity which
										is against the interest of the website or we find you are
										using information available on the platform for any other
										commercial purpose.
									</Text>

									<Text style={styles.numberedItem}>
										7.4 When we terminate your registration, you will not have
										access to your Account. However, this will not affect your
										obligation to repay the amount you have borrowed under a
										Loan Agreement. Or receive EMI Amount you have lent under a
										Loan Agreement.
									</Text>

									<Text style={styles.sectionTitle}>
										8. Indemnity
									</Text>

									<Text style={styles.subSectionTitle}>
										8.1 Service Communications
									</Text>

									<Text style={styles.paragraph}>
										We understand your concerns of not sending unnecessary
										calls, emails or SMS to you. There are some messages
										(&quot;Service Messages&quot;) that we will need to send
										you. These may be sent via email, call or text message and
										include notifications at various stages of your loan.
									</Text>

									<Text style={styles.subSectionTitle}>
										8.2 Occasional Updates
									</Text>

									<Text style={styles.paragraph}>
										When you register on MoneyTime Technology Solutions Pvt.
										Ltd. you are offered the option to receive our occasional
										updates. These messages notify you about new features added
										on the App/ Website, ask your opinion regarding various
										situations and services, and tell you about services you
										might not be using yet. If you decide you no longer want to
										receive these messages you can change your contact
										preferences in the &quot;My Contact Preferences&quot; area
										once you are logged in to your MoneyTime Technology
										Solutions Pvt. Ltd. Account or email your preference to us
										at <Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("mailto:support@rapidmoney.in")}>support@rapidmoney.in</Text>
									</Text>

									<Text style={styles.subSectionTitle}>
										8.3 Redirects, Third Party Links and Offers
									</Text>

									<Text style={styles.paragraph}>
										When you use the App or Website, you may access a link that
										directs you to a third-party website or resource. Such
										websites or resources are not controlled by the Company and
										different terms of use and privacy policy may apply for
										accessing / using such websites or resources. Since the
										Company has no control over such third party websites and
										resources, you acknowledge and agree that Company is not
										responsible for the availability of such external sites or
										resources, and does not endorse and is not responsible or
										liable for any content, advertising, products or other
										materials on or available from such sites or resources. You
										further acknowledge and agree that Company shall not be
										responsible or liable, directly or indirectly, for any
										damage or loss caused or alleged to be caused by or in
										connection with use of or reliance on any such content,
										goods or services available on or through any such site or
										resource. Your interaction with any third party accessed
										through the App / Website is at your own risk, and Company
										will have no liability with respect to the acts, omissions,
										errors, representations, warranties, breaches or negligence
										of any such third parties or for any personal injuries,
										death, property damage, or other damages or expenses
										resulting from your interactions with the third parties. The
										Company disclaims all liability arising from your access to
										or use of such third-party sites.
									</Text>

									<Text style={styles.sectionTitle}>9. Use of Content</Text>

									<Text style={styles.paragraph}>
										While using the App/ Website, the User specifically
										undertakes not to host, display, upload, modify, publish,
										transmit, update or share any information or content that:
									</Text>

									<Text style={styles.listItem}>
										(i) belongs to another person and to which the User does not
										have any right to;
									</Text>

									<Text style={styles.listItem}>
										(ii) is grossly harmful, harassing, blasphemous, defamatory,
										obscene, pornographic, pedophilic, libelous, invasive of
										another&apos;s privacy, hateful, or racially, ethnically
										objectionable, disparaging, relating or encouraging money
										laundering or gambling, or otherwise unlawful in any manner
										whatsoever;
									</Text>

									<Text style={styles.listItem}>
										(iii) harms minors in any way;
									</Text>

									<Text style={styles.listItem}>
										(iv) impersonate any person or entity, or falsely state or
										otherwise misrepresent the User&apos;s affiliation with a
										person or entity;
									</Text>

									<Text style={styles.listItem}>
										(v) threatens the unity, integrity, defense, security or
										sovereignty of India, friendly relations with foreign states
										or public order or causes incitement to the commission of
										any cognizable offence or prevents investigation of any
										offence or is insulting of any other nation;
									</Text>

									<Text style={styles.listItem}>
										(vi) infringes any patent, trademark, copyright or other IPR
										(defined below);
									</Text>

									<Text style={styles.listItem}>
										(vii) contain software viruses or any other computer code,
										files or programs designed to interrupt destroy or limit the
										functionality of any computer resource;
									</Text>

									<Text style={styles.listItem}>
										(viii) deceives or misleads the addressee about the origin
										of such messages or communicates any information which is
										grossly offensive or menacing in nature;
									</Text>

									<Text style={styles.listItem}>
										(ix) engage in any activity that interferes with or disrupts
										access to the App/ Website or the Products (or the servers
										and networks which are connected to the App/ Website);
									</Text>

									<Text style={styles.listItem}>
										(x) attempt to gain unauthorized access to any portion or
										feature of the App/ Website, any other systems or networks
										connected to the App/ Website, to any App/ Website server,
										or to any of the Products offered on or through the App/
										Website, by hacking, password mining or any other
										illegitimate means;
									</Text>

									<Text style={styles.listItem}>
										(xi) probe, scan or test the vulnerability of the App/
										Website or any network connected to the App/ Website, nor
										breach the security or authentication measures on the
										Website or any network connected to the App/ Website;
									</Text>

									<Text style={styles.listItem}>
										(xii) disrupt or interfere with the security of, or
										otherwise cause harm to, the App/ Website, systems
										resources, accounts, passwords, servers or networks
										connected to or accessible through the App/ Website or any
										affiliated or linked sites;
									</Text>

									<Text style={styles.listItem}>
										(xiii) use the App/ Website or content therein for any
										purpose that is unlawful or prohibited by the Terms of Use,
										or to solicit the performance of any illegal activity or
										other activity which infringes the rights of the App/
										Website or other third parties;
									</Text>

									<Text style={styles.listItem}>
										(xiv) falsify or delete any author attributions, legal or
										other proper notices or proprietary designations or labels
										of the origin or source of software or other material
										contained in a file that is uploaded;
									</Text>

									<Text style={styles.listItem}>
										(xv) violate any code of conduct or other guidelines, which
										may be applicable for or to any particular service;
									</Text>

									<Text style={styles.listItem}>
										(xvi) violate any applicable laws or regulations for the
										time being in force within or outside India;
									</Text>

									<Text style={styles.sectionTitle}>
										10. Intellectual Property Rights
									</Text>

									<Text style={styles.numberedItem}>
										10.1 Intellectual Property Rights (&quot;IPR&quot;) for the
										purpose of these Terms of Use shall always mean and include
										copyrights whether registered or not, patents including
										rights of filing patents, trademarks, trade names, trade
										dresses, house marks, collective marks, associate marks and
										the right to register them, designs both industrial and
										layout, geographical indicators, moral rights, broadcasting
										rights, displaying rights, distribution rights, selling
										rights, abridged rights, translating rights, reproducing
										rights, performing rights, communicating rights, adapting
										rights, circulating rights, protected rights, joint rights,
										reciprocating rights, infringement rights and further shall
										also include but not be limited to all text, graphics, user
										interfaces, visual interfaces, sounds and music (if any),
										artwork and computer code in relation to the Website.
									</Text>

									<Text style={styles.numberedItem}>
										10.2 All IPR on the App/ Website exclusively belong to
										either the App/ Website or the third party sellers and
										suppliers, as the case may be. Under no circumstance shall
										any User infringe in any way such IPR of the App/ Website, a
										third party supplier or seller during or pursuant to its use
										of the App/ Website for any purposes whatsoever.
									</Text>

									<Text style={styles.numberedItem}>
										10.3 All those IPR arising as a result of domain names,
										internet or any other right available under applicable law
										shall vest in the domain of <Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("https://www.rapidmoney.in")}>www.rapidmoney.in</Text> as the owner
										of such domain name.
									</Text>

									<Text style={styles.numberedItem}>
										10.4 The Parties hereto agree and confirm that no part of
										any IPR mentioned hereinabove is transferred in the name of
										User and any IPR arising as a result of these presents shall
										also be in the absolute ownership, possession and our
										control or control of its owners/permitted assigns, as the
										case may be.
									</Text>

									<Text style={styles.numberedItem}>
										10.5 Except as expressly provided herein, the User
										acknowledges and agrees that it shall not copy, republish,
										post, display, translate, transmit, reproduce or distribute
										or in any other way infringe any IPR through any medium
										without obtaining the necessary authorization from the App/
										Website or the thirty party owner of such IPR.
									</Text>

									<Text style={styles.sectionTitle}>11. Indemnity</Text>

									<Text style={styles.numberedItem}>
										11.1 The User hereby indemnifies, defends and holds harmless
										the entity owning and operating the Website, its vendors,
										agents and their respective directors, officers, employees,
										contractors and agents (hereinafter individually and
										collectively referred to as &quot;indemnified parties&quot;)
										from and against any and all losses, liabilities, claims,
										suits, proceedings, penalties, interests, damages, demands,
										costs and expenses (including legal and other statutory fees
										and disbursements in connection therewith and interest
										chargeable thereon) asserted against or incurred by the
										indemnified parties that arise out of, result from, or in
										connection with:
									</Text>

									<Text style={styles.listItem}>
										(i) The User&apos;s breach of these Terms of Use; or
									</Text>

									<Text style={styles.listItem}>
										(ii) Any claims made by any third party due to, or arising
										out of, or in connection with, the User&apos;s use of the
										Application/Website; or
									</Text>

									<Text style={styles.listItem}>
										(iii) Any claim that any third party IPR, proprietary
										information, content or materials provided by the User
										causes any damage to a third party; or
									</Text>

									<Text style={styles.listItem}>
										(iv) Violation of any rights of any third party by the User,
										including any IPR; each an &quot;Indemnity Event&quot;.
									</Text>

									<Text style={styles.numberedItem}>
										11.2 Upon occurrence of an Indemnity Event, the
										Application/Website may notify the User of any claims which
										the User shall be liable to indemnify the
										Application/Website against. The User shall then be
										obligated to consult with the Application/Website regarding
										the course of action to be undertaken in defending such a
										claim.
									</Text>

									<Text style={styles.numberedItem}>
										11.3 The User shall not compromise or settle any claim or
										admit any liability or wrongdoing on the part of the Website
										without the express prior written consent of the Website
										which can be withheld or denied or conditioned by the
										Website in its sole discretion.
									</Text>

									<Text style={styles.numberedItem}>
										11.4 Notwithstanding anything to contrary, in no event shall
										the Application/Website, its subsidiaries or affiliates and
										their respective officers, directors, employees, partners or
										suppliers be liable to the User for any special, incidental,
										indirect, consequential, exemplary or punitive damages
										whatsoever, including those resulting from loss of use, data
										or profits, whether or not foreseeable or whether or not the
										Application/Website has been advised of the possibility of
										such damages, or based on any theory of liability, including
										breach of contract or warranty, negligence or other tortious
										action, or any other claim arising out of or in connection
										with the User&apos;s use of or access to the
										Application/Website or the Product.
									</Text>

									<Text style={styles.sectionTitle}>
										12. Report Abuse and Take Down Policy
									</Text>

									<Text style={styles.numberedItem}>
										12.1 In the event the Application/Website or any User
										becomes aware of any objectionable content on the
										Application/Website including but not limited to violation
										of privacy, misuse of personal information or violation of
										any IPR, in violation of these Terms of Use then, the
										Application/Website, by itself or upon receipt of a
										communication from any of its Users, without any prior
										notice take down such objectionable content from the
										Application/Website.
									</Text>

									<Text style={styles.numberedItem}>
										12.2 For any reporting in respect of the aforesaid, the User
										should contact the Application/Website at{" "}
										<Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("mailto:support@rapidmoney.in")}>support@rapidmoney.in</Text>
									</Text>

									<Text style={styles.numberedItem}>
										12.3 If a feedback comment or any communication made between
										Users and the Application/Website or email communication
										between Users in relation to transactions conducted on the
										Application/Website contain profanity, please submit a
										request for action/removal. Disciplinary action may result
										in the indefinite suspension of a User&apos;s account,
										temporary suspension, or a formal warning.
									</Text>

									<Text style={styles.numberedItem}>
										12.4 The Application/Website shall consider the
										circumstances of an alleged policy violation and the
										User&apos;s trading records before taking action; violations
										of this policy may result in a range of actions, including:
										(a) limits placed on account privileges; (b) loss of special
										status; (c) account suspension.
									</Text>

									<Text style={styles.sectionTitle}>
										13. Feedback and Information
									</Text>

									<Text style={styles.numberedItem}>
										13.1 The Application/Website reserves the right, at its sole
										discretion to use such information for upgrading/enhancing
										the Application/Website and such use shall be entirely
										unrestricted.
									</Text>

									<Text style={styles.numberedItem}>
										13.2 The Application/Website may, at its discretion, also
										make any modifications or changes to the RapidMoney Application/Website
										and its content on the basis of such feedback or
										information.
									</Text>

									<Text style={styles.numberedItem}>
										13.3 In the event that the Application/Website makes any
										changes or modifications to the Website on the basis of any
										such feedback, the User shall not have any rights or title
										(including any IPR) in such changes or modifications to the
										Application/Website or Products listed therein.
									</Text>

									<Text style={styles.numberedItem}>
										13.4 By submitting any feedback or any information, the User
										hereby warrants that (i) the feedback does not contain
										confidential or proprietary information belonging to the
										User or any other person; and (ii) shall not be entitled to
										any compensation or reimbursement of any kind from the
										Application/Website for the feedback under any
										circumstances.
									</Text>

									<Text style={styles.sectionTitle}>14. Applicable Law</Text>

									<Text style={styles.paragraph}>
										These Terms of Use shall be governed by and interpreted and
										construed in accordance with the laws of India. The courts
										in Mumbai shall have exclusive jurisdiction in respect of
										any matters arising here from.
									</Text>

									<Text style={styles.sectionTitle}>15. Dispute Resolution</Text>

									<Text style={styles.numberedItem}>
										15.1 In the event any dispute arises out of or in connection
										with the Terms of Use herein, including the validity hereof,
										the parties hereto shall endeavor to settle such dispute
										amicably in the first instance. The attempt to bring about
										an amicable settlement shall be treated as having failed as
										soon as one of the parties hereto, after reasonable
										attempts, which shall continue for not less than 15
										(Fifteen) calendar days, gives a notice to this effect, to
										the other party in writing.
									</Text>

									<Text style={styles.numberedItem}>
										15.2 In case of such failure, the dispute shall be referred
										to a sole arbitrator, who shall be appointed by the Website.
										The arbitration proceedings shall be governed by the Indian
										Arbitration and Conciliation Act, 1996 and shall be held in
										Mumbai. The language of arbitration shall be English.
									</Text>

									<Text style={styles.sectionTitle}>
										16. Jurisdictional Issues
									</Text>

									<Text style={styles.paragraph}>
										Unless otherwise specified, the products/items listed on the
										Application/Website are solely for the purpose of delivery
										in India. The Application/Website shall under no
										circumstance be held liable for use or availability of
										Products for use in locations/countries other than India.
									</Text>

									<Text style={styles.sectionTitle}>
										17. Buyer Protection Program
									</Text>

									<Text style={styles.numberedItem}>
										17.1 If you want to make a complaint about the Loan
										Agreement you can email <Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("mailto:support@rapidmoney.in")}>support@rapidmoney.in</Text> with brief
										details of your complaint and your account reference.
										MoneyTime Technology Solutions Pvt. Ltd. will acknowledge
										your complaint within one working day. MoneyTime Technology
										Solutions Pvt. Ltd. will then investigate and send you an
										initial response within 15 working days.
									</Text>

									<Text style={styles.numberedItem}>
										17.2 If you are not satisfied with the response received, or
										if the customer does not receive any response within 15
										working days, then the customer can write, mail, or call the
										Grievance Redressal Officer of the company which is defined
										in the Grievance Redressal Mechanism.
									</Text>

									<Text style={styles.sectionTitle}>18. General Provisions</Text>

									<Text style={styles.numberedItem}>
										18.1 Notice: All notices to be issued pursuant to these
										Terms of Use shall be served to the User by email or by
										general notification on the Website. Any notice to be sent
										to the Website pursuant to these Terms of Use shall be sent
										to the Application/Website&apos;s grievance officer by
										e-mail at <Text style={{ color: dark_primary, textDecorationLine: "underline" }} onPress={() => Linking.openURL("mailto:support@rapidmoney.in")}>support@rapidmoney.in</Text>
									</Text>

									<Text style={styles.numberedItem}>
										18.2 Assignment: These Terms of Use shall not be assigned or
										otherwise transferred by the User. However the
										Application/Website&apos;s obligations under these Terms of
										Use are freely assignable or otherwise transferable by the
										Application/Website to any third parties without the
										requirement of seeking the Users prior consent.
									</Text>

									<Text style={styles.numberedItem}>
										18.3 Severability: If any provision of these Terms of Use is
										void, or is so declared, such provision shall be severed.
										The Terms of Use shall otherwise remain in full force and
										effect.
									</Text>

									<Text style={styles.numberedItem}>
										18.4 Waiver: Any failure or delay by a party to enforce or
										exercise any provision of these Terms of Use, or any related
										right, shall not constitute a waiver by such party of that
										provision or right. The exercise of one or more of a
										party&apos;s rights hereunder shall not be a waiver of, or
										preclude the exercise of, any rights or remedies available
										to such party under these Terms of Use or in law or at
										equity. Any waiver by a party shall only be made in writing
										and executed by a duly authorized officer of such party.
									</Text>

									<Text style={styles.numberedItem}>
										18.5 Relationship and Exclusivity. Nothing in these Terms of
										Use shall constitute or be deemed to constitute a
										partnership, joint venture, agency or the like between the
										parties hereto or confer on any party any authority to bind
										the other party or to contract in the name of the other
										party or to incur any liability or obligation on behalf of
										the other party.
									</Text>

									<Text style={styles.numberedItem}>
										18.6 Force Majeure: If performance of any service under
										these Terms of Use by the Application/Website is prevented,
										restricted, delayed or interfered with by reason of labor
										disputes, strikes, acts of God, floods, lightning, severe
										weather, shortages of materials, rationing, inducement of
										any virus, Trojan or other disruptive mechanisms, any event
										of hacking or illegal usage of the Application/Website,
										utility or communication failures, earthquakes, war,
										revolution, acts of terrorism, civil commotion, acts of
										public enemies, blockade, embargo or any law, order,
										proclamation, regulation, ordinance, demand or requirement
										having legal effect of any government or any judicial
										authority or representative of any such government, or any
										other act whatsoever, whether similar or dissimilar to those
										referred to in this clause, which are beyond the reasonable
										control of the Application/Website and could not have been
										prevented by reasonable precautions then the
										Application/Website shall in to be excused and discharged
										from such performance to the extent of and during the period
										of such force majeure event, and such non-performance shall,
										in no manner whosoever, amount to a breach by the
										Application/Website of its obligations herein.
									</Text>

									<Text style={styles.sectionTitle}>19. Defined Terms</Text>

									<Text style={styles.numberedItem}>
										19.1 In these T&C the following words have the following
										meanings:
									</Text>

									{/* Table */}
									<View style={styles.table}>
										<View style={styles.tableRow}>
											<View style={styles.tableCell}>
												<Text style={styles.tableCellText}>Borrower</Text>
											</View>
											<View style={styles.tableCell}>
												<Text style={styles.tableCellText}>
													means the person who is registered as a borrower
													on the Website
												</Text>
											</View>
										</View>
										<View style={styles.tableRow}>
											<View style={styles.tableCell}>
												<Text style={styles.tableCellText}>
													Credit Bureau Information
												</Text>
											</View>
											<View style={styles.tableCell}>
												<Text style={styles.tableCellText}>
													means CIBIL, Experian, Equifax and Crif Highmark
												</Text>
											</View>
										</View>
										<View style={styles.tableRow}>
											<View style={styles.tableCell}>
												<Text style={styles.tableCellText}>
													Prohibited Sectors
												</Text>
											</View>
											<View style={styles.tableCell}>
												<Text style={styles.tableCellText}>
													means any business area which is prohibited by
													the Government of India.
												</Text>
											</View>
										</View>
										<View style={styles.tableRow}>
											<View style={styles.tableCell}>
												<Text style={styles.tableCellText}>RBI</Text>
											</View>
											<View style={styles.tableCell}>
												<Text style={styles.tableCellText}>
													means the Reserve Bank of India
												</Text>
											</View>
										</View>
									</View>

									{/* <Text style={styles.paragraph}>Last updated: January 2025</Text> */}

									{/* Add some bottom padding for better scrolling */}
									<View style={styles.bottomPadding} />
								</View>
							</ScrollView>

							{/* Fixed Close Button */}
							<View style={styles.buttonContainer}>
								<TouchableOpacity style={styles.closeButton} onPress={handleClose}>
									<Text style={styles.closeButtonText}>Okay</Text>
								</TouchableOpacity>
							</View>
						</View>
					</SafeAreaView>
				)}

				{language === "hindi" && (
					<SafeAreaView style={styles.container}>
						<View style={styles.modalContent}>
							{/* Header */}
							<View style={styles.header}>
								<Text style={styles.title}>
									नियम और शर्तें (Terms & Conditions)
								</Text>
							</View>

							{/* Scrollable Content */}
							<ScrollView
								style={styles.scrollContainer}
								showsVerticalScrollIndicator={true}>
								<View style={styles.content}>
									{/* ऋण सेवाओं के लिए नियम और शर्तें */}
									<Text style={styles.mainTitle}>
										ऋण सेवाओं के लिए नियम और शर्तें
									</Text>

									<Text style={styles.paragraph}>
										यह वेबसाइट MoneyTime Technology Solutions Pvt. Ltd. (&quot;MTTS&quot;)
										के स्वामित्व और संचालन में है, जो कि कंपनी अधिनियम, 2013 के
										अंतर्गत पंजीकृत एक ऋण सेवा प्रदाता (Loan Service Provider - LSP) है।
									</Text>

									<Text style={styles.paragraph}>
										MTTS केवल ऋण सेवा प्रदाता के रूप में कार्य करता है और ऋण की
										स्वीकृति, मूल्य निर्धारण या अंडरराइटिंग में शामिल नहीं है।
										ये सभी कार्य केवल हमारे साझेदार विनियमित संस्थाओं (Regulated
										Entities - RE) द्वारा किए जाते हैं।
									</Text>

									<Text style={styles.paragraph}>
										यह दस्तावेज / उपयोग की शर्तें (&quot;Terms&quot;) सामान्य नियम और
										शर्तें निर्धारित करता है, जो कि{" "}
										<Text
											style={[styles.paragraph, { color: dark_primary, textDecorationLine: "underline" }]}
											onPress={() => Linking.openURL("https://www.rapidmoney.in")}>
											https://www.rapidmoney.in
										</Text>
										{" "}(&quot;Website&quot;) और इसके मोबाइल एप्लिकेशन &apos;RapidMoney&apos; (&quot;App&quot;)
										के उपयोग पर लागू होती हैं।
									</Text>

									<Text style={styles.paragraph}>
										ये नियम आपके (उपयोगकर्ता) और कंपनी के बीच एक कानूनी रूप से
										बाध्यकारी समझौता हैं।
									</Text>

									{/* इलेक्ट्रॉनिक रिकॉर्ड */}
									<Text style={styles.sectionTitle}>इलेक्ट्रॉनिक रिकॉर्ड</Text>
									<Text style={styles.paragraph}>
										यह समझौता सूचना प्रौद्योगिकी अधिनियम, 2000 के तहत एक
										इलेक्ट्रॉनिक रिकॉर्ड है, जिसे किसी कंप्यूटर प्रणाली द्वारा
										उत्पन्न किया गया है और इसमें किसी भौतिक या डिजिटल हस्ताक्षर
										की आवश्यकता नहीं है।
									</Text>

									{/* नियमों में संशोधन */}
									<Text style={styles.sectionTitle}>नियमों में संशोधन</Text>
									<Text style={styles.paragraph}>
										कंपनी को अधिकार है कि वह किसी भी समय:
									</Text>
									<Text style={styles.listItem}>
										• इन शर्तों में संशोधन, जोड़ या हटाने का अधिकार रखती है।
									</Text>
									<Text style={styles.listItem}>
										• वेबसाइट / ऐप पर सामग्री में बदलाव कर सकती है।
									</Text>
									<Text style={styles.paragraph}>
										यदि किसी भी नियम को अवैध, शून्य या अनुपालन योग्य न पाया गया,
										तो वह नियम अलग कर दिया जाएगा और बाकी नियम वैध रहेंगे।
										वेबसाइट और ऐप का निरंतर उपयोग करना इन परिवर्तनों को स्वीकार
										करना माना जाएगा।
									</Text>

									{/* सहमति */}
									<Text style={styles.sectionTitle}>सहमति</Text>
									<Text style={styles.paragraph}>
										MTTS की सेवाओं का उपयोग करते हुए आप सहमति देते हैं कि:
									</Text>
									<Text style={styles.listItem}>
										• आपकी व्यक्तिगत और वित्तीय जानकारी को कंपनी अपने साझेदारों
										के साथ साझा कर सकती है, ताकि आपको अन्य वित्तीय उत्पादों और
										सेवाओं की पेशकश की जा सके।
									</Text>
									<Text style={styles.listItem}>
										• आपकी जानकारी का उपयोग हमारी गोपनीयता नीति (Privacy Policy)
										के अनुसार किया जाएगा।
									</Text>

									{/* ग्राहक पात्रता (Eligibility) */}
									<Text style={styles.sectionTitle}>
										ग्राहक पात्रता (Eligibility)
									</Text>
									<Text style={styles.paragraph}>
										केवल वही व्यक्ति ऐप/वेबसाइट का उपयोग कर सकते हैं जो
										भारतीय अनुबंध अधिनियम, 1872 के तहत कानूनी रूप से अनुबंध करने
										योग्य हैं।
									</Text>
									<Text style={styles.paragraph}>
										निम्न उपयोग करने के पात्र नहीं हैं:
									</Text>
									<Text style={styles.listItem}>
										• नाबालिग
									</Text>
									<Text style={styles.listItem}>
										• दिवालिया (Insolvent)
									</Text>
									<Text style={styles.sectionTitle}>
										प्रतिभागी (Participants)
									</Text>
									<Text style={styles.listItem}>
										• 18 वर्ष से अधिक आयु का होना चाहिए।
									</Text>
									<Text style={styles.listItem}>
										• भारत में वैध बैंक खाता और PAN कार्ड / आधार (KYC दस्तावेज) होना चाहिए।
									</Text>
									<Text style={styles.listItem}>
										• पिछले 6 महीनों में बेरोजगार / व्यवसाय बंद नहीं होना चाहिए।
									</Text>
									<Text style={styles.listItem}>
										• किसी भी नागरिक या आपराधिक मुकदमे में शामिल नहीं होना चाहिए।
									</Text>

									{/* पंजीकरण */}
									<Text style={styles.sectionTitle}>पंजीकरण</Text>
									<Text style={styles.listItem}>
										• उपयोगकर्ताओं को ऐप/वेबसाइट पर खाता बनाना होगा।
									</Text>
									<Text style={styles.listItem}>
										• पंजीकरण के दौरान KYC और क्रेडिट ब्यूरो जांच की जाएगी।
									</Text>

									{/* वेबसाइट का उपयोग */}
									<Text style={styles.sectionTitle}>वेबसाइट का उपयोग</Text>
									<Text style={styles.listItem}>
										• केवल पंजीकृत उपयोगकर्ता ही ऋण आवेदन कर सकते हैं।
									</Text>
									<Text style={styles.listItem}>
										• उपयोगकर्ता अपने खाते से की गई सभी गतिविधियों के लिए स्वयं जिम्मेदार होंगे।
									</Text>
									<Text style={styles.listItem}>
										• हैकिंग, धोखाधड़ी या अवैध कार्य पाए जाने पर खाता निलंबित किया जा सकता है।
									</Text>

									{/* ऋण शर्तें */}
									<Text style={styles.sectionTitle}>ऋण शर्तें</Text>
									<Text style={styles.listItem}>
										• ऋण प्राप्त करने के लिए उधारकर्ता को Loan Request पोस्ट करनी होगी।
									</Text>
									<Text style={styles.listItem}>
										• बैंक खाता विवरण देना अनिवार्य है।
									</Text>
									<Text style={styles.listItem}>
										• ऋण स्वीकृत होने पर Key Fact Statement और Loan Agreement डिजिटल रूप से साइन करना होगा।
									</Text>
									<Text style={styles.listItem}>
										• ऋण राशि सीधे उधारकर्ता के बैंक खाते में स्थानांतरित की जाएगी।
									</Text>

									{/* शुल्क और खर्च */}
									<Text style={styles.sectionTitle}>शुल्क और खर्च</Text>
									<Text style={styles.listItem}>
										• प्रोसेसिंग शुल्क: 15% तक (डिसबर्समेंट पर लागू)
									</Text>
									<Text style={styles.listItem}>
										• विलंब शुल्क (Late Payment Fee): समय पर EMI न चुकाने पर लागू
									</Text>
									<Text style={styles.listItem}>
										• मुकदमा खर्च: कानूनी वसूली की स्थिति में उधारकर्ता से लिया जाएगा।
									</Text>

									{/* गोपनीयता और डेटा सुरक्षा */}
									<Text style={styles.sectionTitle}>
										गोपनीयता और डेटा सुरक्षा
									</Text>
									<Text style={styles.listItem}>
										• आवश्यक सेवा संदेश SMS / Email / Call के माध्यम से भेजे जाएंगे।
									</Text>
									<Text style={styles.listItem}>
										• उपयोगकर्ताओं को समय-समय पर प्रमोशनल अपडेट्स मिल सकते हैं।
									</Text>
									<Text style={styles.listItem}>
										• ऐप/वेबसाइट पर दिए गए थर्ड-पार्टी लिंक के लिए कंपनी जिम्मेदार नहीं होगी।
									</Text>

									{/* बौद्धिक संपदा अधिकार (Intellectual Property Rights) */}
									<Text style={styles.sectionTitle}>
										बौद्धिक संपदा अधिकार (Intellectual Property Rights)
									</Text>
									<Text style={styles.paragraph}>
										वेबसाइट और ऐप पर उपलब्ध सभी सामग्री, कोड, टेक्स्ट,
										ग्राफिक्स, डिज़ाइन और ट्रेडमार्क MTTS या उसके साझेदारों के
										अधिकार में हैं।
									</Text>

									{/* दायित्व से विमुक्ति (Indemnity) */}
									<Text style={styles.sectionTitle}>
										दायित्व से विमुक्ति (Indemnity)
									</Text>
									<Text style={styles.paragraph}>
										उपयोगकर्ता सहमत है कि यदि उसकी गतिविधियों से कंपनी या उसके
										साझेदारों को कोई नुकसान होता है, तो वह पूरी तरह जिम्मेदार
										होगा।
									</Text>

									{/* लागू कानून (Applicable Law) */}
									<Text style={styles.sectionTitle}>
										लागू कानून (Applicable Law)
									</Text>
									<Text style={styles.paragraph}>
										ये शर्तें भारत के कानूनों द्वारा शासित होंगी और मुंबई
										(Maharashtra) के न्यायालयों को विशेष अधिकार होगा।
									</Text>

									<View style={styles.bottomPadding} />
								</View>
							</ScrollView>

							{/* Fixed Close Button */}
							<View style={styles.buttonContainer}>
								<TouchableOpacity style={styles.closeButton} onPress={handleClose}>
									<Text style={styles.closeButtonText}>ठीक है</Text>
								</TouchableOpacity>
							</View>
						</View>
					</SafeAreaView>
				)}
			</View>
		</Modal>
	);
};

const styles = StyleSheet.create({
	backdrop: {
		flex: 1,
		backgroundColor: "rgba(0, 0, 0, 0.5)",
		justifyContent: "center",
		alignItems: "center",
	},
	container: {
		flex: 1,
		width: "100%",
		paddingHorizontal: 20,
		paddingVertical: 40,
		height: height(80),
	},
	modalContent: {
		flex: 1,
		backgroundColor: "#ffffff",
		borderRadius: 12,
		overflow: "hidden",
	},
	header: {
		padding: 20,
		borderBottomWidth: 0.3,
		// borderBottomColor: "#e0e0e0",
		backgroundColor: "#f8f9fa",
	},
	title: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#333",
		textAlign: "center",
	},
	scrollContainer: {
		flex: 1,
	},
	content: {
		padding: 20,
	},
	mainTitle: {
		fontSize: 20,
		fontWeight: "bold",
		color: "#333",
		textAlign: "center",
		marginBottom: 20,
	},
	paragraph: {
		fontSize: 14,
		lineHeight: 22,
		color: "#444",
		marginBottom: 16,
		textAlign: "justify",
	},
	sectionTitle: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#333",
		marginTop: 24,
		marginBottom: 12,
	},
	subSectionTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		marginTop: 20,
		marginBottom: 10,
	},
	numberedItem: {
		fontSize: 14,
		lineHeight: 22,
		color: "#444",
		marginBottom: 12,
		textAlign: "justify",
	},
	subNumberedItem: {
		fontSize: 14,
		lineHeight: 22,
		color: "#444",
		marginBottom: 8,
		paddingLeft: 20,
		textAlign: "justify",
	},
	listItem: {
		fontSize: 14,
		lineHeight: 20,
		color: "#444",
		marginBottom: 8,
		paddingLeft: 10,
	},
	subListTitle: {
		fontSize: 14,
		lineHeight: 22,
		color: "#444",
		marginBottom: 8,
		textAlign: "justify",
	},
	table: {
		borderWidth: 1,
		borderColor: "#ddd",
		marginVertical: 16,
	},
	tableRow: {
		flexDirection: "row",
		borderBottomWidth: 1,
		borderBottomColor: "#ddd",
	},
	tableCell: {
		flex: 1,
		padding: 12,
		borderRightWidth: 1,
		borderRightColor: "#ddd",
	},
	tableCellText: {
		fontSize: 14,
		color: "#444",
		lineHeight: 20,
	},
	bottomPadding: {
		height: 20,
	},
	buttonContainer: {
		padding: 20,
		borderTopWidth: 1,
		borderTopColor: "#e0e0e0",
		backgroundColor: "#f8f9fa",
	},
	closeButton: {
		backgroundColor: primary,
		paddingVertical: 12,
		paddingHorizontal: 24,
		borderRadius: 8,
		alignItems: "center",
	},
	closeButtonText: {
		color: dark,
		fontSize: 16,
		fontWeight: "600",
	},
});
